name: CI (main)

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Backend CI (main)
    uses: ./.github/workflows/node-ci-reusable.yml
    with:
      working-directory: backend
      run-build: true

  frontend:
    name: Frontend CI (main)
    uses: ./.github/workflows/node-ci-reusable.yml
    with:
      working-directory: frontend
      run-build: true
