name: CI (PR)

on:
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend CI (PR)
    uses: ./.github/workflows/node-ci-reusable.yml
    with:
      working-directory: backend
      run-build: false

  frontend:
    name: Frontend CI (PR)
    uses: ./.github/workflows/node-ci-reusable.yml
    with:
      working-directory: frontend
      run-build: false
